### ISSUE TITLE
Question: hot reloading / live reloading / watch mode

### ISSUE THREAD

**Issue by boustanihani** [egoist/vbuild#117]
Could anyone please explain the difference between:
- hot reloading
- live reloading
- watch mode

and maybe how each mode is activated...

**Comment by egoist** [comment]
`--dev` mode uses hot reloading by default, when your file does not support hot reloading it fallbacks to live reloading.

`--watch` can be used with/without `-dev` flags:

- with `--dev`: no dev server, no hot reloading, since you may not need to open browser at all. It only rebuilt when file changes, all other features in `dev` is the same, .
- without `--dev`: like production mode but it rebuilt due to file changes.

**Comment by boustanihani** [comment]
Thanks a lot
