### ISSUE TITLE
Allow lint rules to be configurable

### ISSUE THREAD

**Issue by zephraph** [egoist/vbuild#24]
Currently your lint rule set is the only one usable. It'd be nice if we could provide our on eslint file and have it use that. Maybe by specifying a path to it? 

There's a big benefit of having an eslint file in the root. It allows editors or IDEs to use it while editing.

**Comment by egoist** [comment]
Oh, I think it's already available via `options.eslint`, I just haven't documented this because it's tested yet 😅

By default it uses a preset config file, you can override it though:

```js
module.exports = {
  lint: true,
  eslint: {
    configFile: cwd('.eslintrc') 
  }
}
```

Will document it after adding more improvements to this.

**Comment by zephraph** [comment]
Sounds good.

**Comment by egoist** [comment]
See https://vbuild.js.org/docs/addons.html#eslint

**Comment by NemoAlex** [comment]
I'm wondering how to do lint in v7. `vbuild --eslint` doesn't work now.

**Comment by egoist** [comment]
@NemoAlex 

If you want to run eslint during building, here's a preset: https://github.com/egoist/vbuild/blob/master/packages/vbuild-preset-eslint/README.md

In fact it's as simple as mutating the webpack config via old `webpack(config) {}` option for new [`extendWebpack(config) {}`](https://vbuild.js.org/#/?id=webpack) option.

Personally I would use eslint or xo directly like `eslint **/src/**/*.{vue,js}`, since it's much faster, see [here](https://github.com/egoist/codepan/blob/master/package.json#L11) for example
