### ISSUE TITLE
Use vbuild as express middleware

### ISSUE THREAD

**Issue by egoist** [egoist/vbuild#90]
```js
const express = require('express')
const vbuild = require('vbuild/mw')

const app = express()
app.use(vbuild({
  // same as vue.config.js
}))
```

**Comment by NemoAlex** [comment]
Is this still available in current versions?
I'm working on a new project which is a module of nuxt.js. I hope poi could run as a express/connect middleware in dev mode so that it could provide a smooth dev experience.
Or I have to do is: start a dev server which listening on a specific port and start a proxy server to pass some requests from nuxt.js to poi dev server.
